/*Consultas Catastro*/
use CATASTRO

--32--
select p.NOMBRE,APELLIDO1,APELLIDO2
from PROPIETARIO p, CASAPARTICULAR c
where p.DNI=c.DNIPROPIETARIO
--from PROPIETARIO p inner join CASAPARTICULAR c
--on p.DNI=c.DNIPROPIETARIO

--33--
select z.NOMBREZONA,NUMPARQUES,v.CALLE,v.NUMERO,v.METROSSOLAR
from ZONAURBANA z, VIVIENDA v
where z.NOMBREZONA=v.NOMBREZONA and
z.NUMPARQUES>1

--34--
select c.CALLE,c.NUMERO,c.NUMPLANTAS,c.METROSCONSTRUIDOS,
v.METROSSOLAR
from VIVIENDA v,CASAPARTICULAR c
where v.CALLE=c.CALLE and v.NUMERO=c.NUMERO

--35--
select z.DESCRIPCIÓN, z.NOMBREZONA
from ZONAURBANA z, VIVIENDA v
where z.NOMBREZONA=v.NOMBREZONA
and z.NUMPARQUES>2 and v.TIPOVIVIENDA='bloque'

--36--
select p.CALLE,p.PUERTA,p.NUMHABITACIONES,p.METROSUTILES,z.NOMBREZONA,z.NUMPARQUES,
pr.NOMBRE,pr.APELLIDO1,pr.APELLIDO2
from PISO p, ZONAURBANA z,VIVIENDA v, PROPIETARIO pr
where z.NOMBREZONA=v.NOMBREZONA and p.DNIPROPIETARIO=pr.DNI
and v.CALLE=p.CALLE and v.NUMERO=p.NUMERO

--37--
select pr.NOMBRE,pr.APELLIDO1,pr.APELLIDO2
from HUECO h,PROPIETARIO pr,VIVIENDA v
where v.CALLE=h.CALLE and v.NUMERO=h.NUMERO and
h.DNIPROPIETARIO=pr.DNI and TIPO='BODEGA' and pr.SEXO='M'
and METROS>9

--38--
select pr.DNI, pr.NOMBRE,pr.APELLIDO1,pr.APELLIDO2
from CASAPARTICULAR c,PROPIETARIO pr
where c.DNIPROPIETARIO=pr.DNI and pr.SEXO='M'

--39--
select p.*, pr.NOMBRE+' '+pr.APELLIDO1+' '+ 
isnull (pr.APELLIDO2,' ') as Nombre_Completo
from PISO p, PROPIETARIO pr, VIVIENDA v,ZONAURBANA z,
BLOQUEPISOS b
where p.DNIPROPIETARIO=pr.DNI and z.NOMBREZONA=v.NOMBREZONA and
v.CALLE=p.CALLE and v.NUMERO=p.NUMERO and 
v.CALLE=b.CALLE and v.NUMERO=b.NUMERO and
((z.NUMPARQUES=2 and p.NUMHABITACIONES between 2 and 4) 
or 
(z.NOMBREZONA='Centro' and p.METROSCONSTRUIDOS between 71 and 109
and b.ASCENSOR='S'))

--40--
Select	LOWER(PR.NOMBRE)+' '+LOWER(PR.APELLIDO1)+' '+LOWER(PR.APELLIDO2) As NombreMinús,
		C.*
From CASAPARTICULAR C, PROPIETARIO PR
Where	C.DNIPROPIETARIO=PR.DNI and PR.SEXO='H'
and PR.TELEFONO Is Not Null and C.NUMPLANTAS=1

--41--

Select V.CALLE, V.NUMERO, V.TIPOVIVIENDA,Z.NOMBREZONA, 
Z.DESCRIPCIÓN
From ZONAURBANA Z left join VIVIENDA V
on V.NOMBREZONA=Z.NOMBREZONA

